/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.29.3
 * source: src/proto/contract/common.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace protocol {
    export enum ResourceCode {
        BANDWIDTH = 0,
        ENERGY = 1,
        TRON_POWER = 2
    }
}
